jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow
# TEST deployment to Kube cluster on AWS
  - name: man-sample-kube
    type: manifest
    steps:
      - IN: img-sample-kube
      - IN: img-opts-sample-kube-test

  - name: kube-deploy-test-sample
    type: deploy
    steps:
      - IN: man-sample-kube
      - IN: cluster-kube
      - IN: params-sample-test-kube
      - TASK: managed
        deployMethod: upgrade

# PROD deployment to Kube cluster on AWS
  - name: kube-deploy-prod-sample
    type: deploy
    steps:
      - IN: kube-deploy-test-sample
      - IN: cluster-kube
      - IN: params-sample-prod-kube
      - IN: replicas-sample-prod-kube
      - TASK: managed
        deployMethod: upgrade
